MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASSWORD = '8a1cc32a93a773b7'
MYSQL_DATABASE = '3ddatabase'

SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://' + MYSQL_USER + ':' + MYSQL_PASSWORD + '@localhost:' + str(MYSQL_PORT) + '/' + MYSQL_DATABASE
SQLALCHEMY_TRACK_MODIFICATIONS = True

